"""Add is_auth and role fields to User

Revision ID: bd657bb5f35c
Revises: ec71989a8c23
Create Date: 2024-05-15 21:04:32.580533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd657bb5f35c'
down_revision = 'ec71989a8c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=255), nullable=True),
    sa.Column('prenume', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('profesie', sa.String(length=255), nullable=True),
    sa.Column('parola', sa.String(length=255), nullable=True),
    sa.Column('is_auth', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('id_institutie', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_institutie'], ['institutii.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
