"""Initial migration.

Revision ID: d039359bbeb9
Revises: 
Create Date: 2024-05-15 20:27:18.261034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd039359bbeb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutii',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=255), nullable=True),
    sa.Column('adresa', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacienti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=255), nullable=True),
    sa.Column('prenume', sa.String(length=255), nullable=True),
    sa.Column('data_nastere', sa.String(length=255), nullable=True),
    sa.Column('varsta', sa.Integer(), nullable=True),
    sa.Column('cnp', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.String(length=255), nullable=True),
    sa.Column('fisa_medicala', sa.String(length=255), nullable=True),
    sa.Column('nr_telefon', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('adresa', sa.String(length=255), nullable=True),
    sa.Column('id_institutie', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_institutie'], ['institutii.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnp'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nume', sa.String(length=255), nullable=True),
    sa.Column('prenume', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('profesie', sa.String(length=255), nullable=True),
    sa.Column('parola', sa.String(length=255), nullable=True),
    sa.Column('id_institutie', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_institutie'], ['institutii.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('pacienti')
    op.drop_table('institutii')
    # ### end Alembic commands ###
